name: Build AxeMobile

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      # ------------------------------
      # LINUX BUILD
      # ------------------------------
      - name: Enable Linux desktop
        if: matrix.os == 'ubuntu-latest'
        run: flutter config --enable-linux-desktop

      - name: Build Linux App
        if: matrix.os == 'ubuntu-latest'
        run: flutter build linux --release

      # ------------------------------
      # ANDROID BUILDS
      # ------------------------------
      - name: Build Android APK
        run: flutter build apk --release

      - name: Build Android AAB
        run: flutter build appbundle --release

      # ------------------------------
      # MAC BUILD
      # ------------------------------
      - name: Enable macOS desktop
        if: matrix.os == 'macos-latest'
        run: flutter config --enable-macos-desktop

      - name: Build macOS App
        if: matrix.os == 'macos-latest'
        run: flutter build macos --release

      # ------------------------------
      # Upload artifacts
      # ------------------------------
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: |
            build/linux/**
            build/macos/**
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/bundle/release/*.aab
