name: Build AxeMobile Tauri App

on:
  push:
    branches:
      - release
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-22.04, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - if: matrix.platform == 'macos-latest'
        run: |
          rustup target add x86_64-apple-darwin --toolchain stable
          rustup target add aarch64-apple-darwin --toolchain stable

      - if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - run: yarn install

      - name: Align Tauri Versions
        run: |
          RUST_TAURI_VERSION=$(grep '^tauri' src-tauri/Cargo.toml \
            | sed -E 's/.*version = ?"([0-9]+\.[0-9]+).*/\1/')
          echo "Aligning @tauri-apps/api and tauri to Rust version $RUST_TAURI_VERSION"
          yarn add "@tauri-apps/api@$RUST_TAURI_VERSION.x" "tauri@$RUST_TAURI_VERSION.x"

      - run: yarn build

      - run: |
          if [[ "${{ matrix.platform }}" == "macos-latest" ]]; then
            yarn tauri build --target x86_64-apple-darwin
            yarn tauri build --target aarch64-apple-darwin
          else
            yarn tauri build
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: AxeMobile-build-${{ matrix.platform }}
          path: src-tauri/target/release/bundle/
